#make -f Makefile

# Set the remove file command for your system used in the clean command
#Rm = del

# Set the required Fortran compiler and associated flags
#F90 = nagfor
#F90FLAGS = -g -g90 -gline -nan -C=all -C=undefined -C=dangling -maxcontin=999 
#F90LINKFLAGS = -g -g90 -gline -nan -C=all -C=undefined -C=dangling -maxcontin=999 
#O = o

#F90 = ifort
#F90FLAGS =  -O3 /WARN:ALL /WARN:DECLARATIONS /STAND:F90 /TRACEBACK /CU
#F90LINKFLAGS = -O3  /WARN:ALL /WARN:DECLARATIONS /STAND:F90 /TRACEBACK /CU
#O = obj

F90 = gfortran
F90FLAGS = -O3  -g -ffast-math 
F90LINKFLAGS = -O3 -g -ffast-math 
O = o

# Templates for .f90->.o and .o -> executable
%.$O: %.f90
	$(F90)  $(F90FLAGS) -o $@ -c $<

%: %.$O
	$(F90) $(F90LINKFLAGS) -o $@ $^

OBJS = set_rk.$O  Faddeyeva_v2_mod_rk.$O Faddeyeva_v3_mod_rk.$O
Faddeyeva_v3_driver_rk:  $(OBJS) Faddeyeva_v3_driver_rk.$O  
Faddeyeva_v3_driver_rk.$O: $(OBJS) 

Faddeyeva_v2_mod_rk.$O: set_rk.$O 
Faddeyeva_v3_mod_rk.$O: set_rk.$O
set_rk.$O: 

#.PHONY: clean
clean:
	# remove all files generated by the compiler
	# these are compiler dependent
	del -f *.$O *.d *.g90 *.mod
	# remove all executables
	del -f $(executables)


